name: 'Unity Build (XRTK)'
description: 'Runs a Build using the specified build targets'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  build-target:
    description: 'The build target to build for.'
    # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
    # StandaloneWindows64, WSAPlayer, StandaloneOSX, iOS, StandaloneLinux64, Android, Lumin, WebGL
    default: ''
  additional-validate-args:
    description: 'Additional args to pass to validate command'
    default: ''
  additional-test-args:
    description: 'Additional args to pass to test command'
    default: ''
  additional-build-args:
    description: 'Additional args to pass to build command'
    default: ''

runs:
  using: "composite"
  steps:
    - id: unity-setup
      name: Unity Editor Setup
      uses: xrtk/unity-setup@v1

    - uses: xrtk/unity-action@refactor
      name: Project Validation
      with:
        name: 'project-validation'
        editor-path: '${{ env.UNITY_EDITOR_PATH }}'
        project-path: '${{ env.UNITY_PROJECT_PATH }}'
        args: '-quit -batchmode -executeMethod XRTK.Editor.BuildPipeline.UnityPlayerBuildTools.ValidateProject ${{ inputs.additional-validate-args }}'

    - uses: xrtk/unity-action@refactor
      name: '${{ inputs.build-target }}-Tests'
      with:
        name: '${{ inputs.build-target }}-Tests'
        editor-path: '${{ env.UNITY_EDITOR_PATH }}'
        project-path: '${{ env.UNITY_PROJECT_PATH }}'
        build-target: '${{ inputs.build-target }}'
        args: '-batchmode -runEditorTests ${{ inputs.additional-test-args }}'

    - uses: xrtk/unity-action@refactor
      name: '${{ inputs.build-target }}-Build'
      with:
        name: '${{ inputs.build-target }}-Build'
        editor-path: '${{ env.UNITY_EDITOR_PATH }}'
        project-path: '${{ env.UNITY_PROJECT_PATH }}'
        build-target: '${{ inputs.build-target }}'
        args: '-quit -batchmode -executeMethod XRTK.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild ${{ inputs.additional-build-args }}'

    - name: Zip Artifacts
      if: always()
      run: |
        # Zip Artifacts
        $artifacts = "${{ env.project-path }}/Builds"

        if (Test-Path -Path $artifacts) {
          Compress-Archive -Path "$artifacts/*" -DestinationPath ${{ github.workspace }}/${{ runner.os }}-${{ inputs.build-target }}-Artifacts.zip -Force
          Remove-Item $artifacts -Force -Recurse
        }
      shell: pwsh

    - uses: actions/upload-artifact@v3
      name: Upload Artifacts
      if: always()
      with:
        name: '${{ runner.os }}-${{ inputs.build-target }}-Artifacts'
        path: '${{ github.workspace }}/${{ runner.os }}-${{ inputs.build-target }}-Artifacts.zip'
