name: unity-build-validation

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2 # Use this if you're activating pro license with matrix
      matrix:
        include:
          - os: ubuntu-latest
            build-target: Android
          - os: windows-latest
            build-target: StandaloneWindows64
          - os: macos-latest
            build-target: Android

    steps:
      - name: checkout self
        uses: actions/checkout@v3

      - name: checkout test project
        uses: actions/checkout@v3
        with:
          repository: xrtk/com.xrtk.test
          path: test-project

        # Installs the Unity Editor based on your project version text file
        # sets -> env.UNITY_EDITOR_PATH
        # sets -> env.UNITY_PROJECT_PATH
        # https://github.com/XRTK/unity-setup
      - uses: xrtk/unity-setup@fix/3.4.1
        with:
          build-targets: ${{ matrix.build-target }}
          version-file-path: 'test-project/**/ProjectSettings/ProjectVersion.txt'

        # Activates the installation with the provided credentials
        # https://github.com/XRTK/activate-unity-license
      - uses: xrtk/activate-unity-license@v2
        with:
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
          serial: ${{ secrets.UNITY_SERIAL }} # Required for pro/plus activations
          license-type: 'Professional' # Chooses license type to use [ Personal, Professional ]

      - name: Unity Build (${{ matrix.build-target }})
        uses: ./ #xrtk/unity-build
        with:
          build-target: ${{ matrix.build-target }}

      - name: Unity Build No Tests (${{ matrix.build-target }})
        uses: ./ #xrtk/unity-build
        with:
          build-target: ${{ matrix.build-target }}
          test: false

      - name: Unity Build No Artifacts (${{ matrix.build-target }})
        uses: ./ #xrtk/unity-build
        with:
          build-target: ${{ matrix.build-target }}
          publish-artifacts: false
